plugins/040-apps/config/routes.rb
Apps::Engine.routes.draw do
	# root of the plugin
	root :to => 'apps#index'
	# examples of controllers built in this generator. delete at will
	match 'installed' => 'apps#installed', via: [:get,:post]

	post 'install/:id' => 'apps#install', as: 'install'
	match 'install_progress/:id' => 'apps#install_progress', as: 'install_progress', via: [:get,:post]

	post 'uninstall/:id' => 'apps#uninstall', as: 'uninstall'
	match 'uninstall_progress/:id' => 'apps#uninstall_progress', as: 'uninstall_progress', via: [:get,:post]

	put 'toggle_in_dashboard/:id' => 'apps#toggle_in_dashboard', as: 'toggle_in_dashboard'
end

plugins/040-apps/app/controllers/apps_controller.rb
# Amahi Home Server
# Copyright (C) 2007-2013 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

class AppsController < ApplicationController

	before_action :admin_required

	# make the JSON calls much more efficient by not invoking these filters
	skip_before_action :before_action_hook, except: [:index, :installed]

	def index
		set_title t('apps')
		@apps = App.available
	end

	def installed
		set_title t('apps')
		@apps = App.latest_first
	end

	# Init app installation after user clicks on install button
	def install
		identifier = params[:id]
		@app = App.where(:identifier=>identifier).first
		App.install identifier unless @app # Check app/models/app.rb for App.install function
	end

	# Used to serve ajax calls for showing app installation progress progress
	def install_progress
		identifier = params[:id]
		@app = App.where(:identifier=>identifier).first

		if @app
			@app.reload
			@progress = @app.install_status
			@message = @app.install_message
		else
			@progress = App.installation_status identifier
			@message = App.installation_message @progress
		end
		# we may send HTML if there app is installed or it errored out
		# Installation errors out if @progress>100 and succedes if @progress=100
		before_action_hook if @progress >= 100
	end

	# Init app uninstall after user clicks on uninstall button
	def uninstall
		identifier = params[:id]
		@app = App.where(:identifier=>identifier).first
		@app.uninstall if @app
	end

	# Used to serve ajax calls for showing app uninstallation progress progress
	def uninstall_progress
		identifier = params[:id]
		@app = App.where(:identifier=>identifier).first
		if @app
			@app.reload
			@progress = @app.install_status
			@message = @app.uninstall_message
		else
			@message = t('application_uninstalled')
			@progress = 0
		end
	end


	def toggle_in_dashboard
		identifier = params[:id]
		app = App.where(:identifier=>identifier).first
		if app.installed
			app.show_in_dashboard = ! app.show_in_dashboard
			app.save
			@saved = true
		end
		render :json => { :status => @saved ? :ok : :not_acceptable }
	end

end

plugins/040-apps/app/helpers/application_helper.rb
module ApplicationHelper
end

plugins/040-apps/app/helpers/apps_helper.rb
# Amahi Home Server
# Copyright (C) 2007-2013 Amahi
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v3
# (29 June 2007), as published in the COPYING file.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# file COPYING for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Amahi
# team at http://www.amahi.org/ under "Contact Us."

module AppsHelper

  def short_desc(app)
    return t('no_description_supplied') unless app.description
    # truncate if too long
    truncate(strip_tags(app.description), length: 90)
  end

  def name_with_warning(app)
    app.testing? ? "#{app.name}<sup>*</sup>".html_safe : app.name
  end

  def image_for_app(app)
    image_tag(app.screenshot_url, :class => 'app-screenshot', :title => "#{app.name} screenshot").html_safe
  end

  def display_app?
    request.xhr?
  end

  def display_style
    request.xhr? ? '' : 'display: none;'
  end

end

plugins/040-apps/app/views/apps/_app_available.html.slim
- app = app_available

= content_tag 'div', :class => 'app', :id => "app_whole_#{app.identifier}", :data => { :progress_path => apps_engine.install_progress_path(app.identifier) } do

  table.settings.stretchtoggle[id="app_row_#{app.identifier}"]
    tr.hover-style
      td.settings-col1.settings-col1-pad1.apps-col1
        = link_to name_with_warning(app), '#'
      td.settings-col2.apps-col2.p-1[id="app_ip_#{app.identifier}"]
        = short_desc(app)

  .settings-stretcher[id="app_info_#{app.identifier}" style="#{display_style}"]
    .app-manage.collapsed-div-style.f-size13.text-secondary
      fieldset
        legend &nbsp; #{app.name} #{t('available_for_installation')} &nbsp;
        .settings-fields.row
          .img-wrap.col-md-6.col-xs-12.col-sm-12.align-items-center.mb-2
            = app.webapp ? link_to(image_for_app(app), app.remote_url, :target => '_blank', :style => 'width: 100%;') : image_for_app(app)

          .app-content.m-0.col-md-6.col-xs-12.col-sm-12
            div.app-description
              = app.description.try(:html_safe) || t('no_description_supplied')

            = render 'is_available', :app => app

            .progress.progress-bar-div.mt-4 style="width: 100%; display: none; background: #c7c7c7;"
              .progress-bar.progress-bar-striped.progress-bar-animated.bg-info aria-valuemax="100" \aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: 0%; height: 100%;"
                = "0%"

            .app-more.top-margin-10
              p
                | #{t('version')} #{app.version}
                = link_to '', app.app_url, :target => '_blank', :class=>'glyphicon glyphicon-plus-sign'

              - if app.forum_url.present?
                br
                = link_to "#{t('discussion_forum_for')} #{app.name}", app.forum_url, :target => '_blank'
                | &raquo;

            - unless app.live?
              p
              em
                sup*
                = t('warning_this_application_is_in_testing')

        .app-flash-notice[id="app_legend_#{app.identifier}" style="display:none;"]
          | #{app.name} #{t('is_now_uninstalled')}

plugins/040-apps/app/views/apps/_app_failed.html.slim
- identifier = "unknown"

= content_tag 'div', :class => 'app', :id => "app_whole_#{identifier}" do

  table.settings.stretchtoggle[id="app_row_#{identifier}"]
    tr style="cursor: pointer;"
      td.settings-col1.settings-col1-pad1.apps-col1
        = link_to '-', '#'
      td.settings-col2.apps-col2[id="app_ip_#{identifier}"]
        | 

  .settings-stretcher.bg-white.mb-2.p-2[id="app_info_#{identifier}" style="#{display_style}"]
    .app-manage
      fieldset
        .settings-fields
          p.app-description
            | This app failed to install &nbsp; :-(  &nbsp; We REALLY HATE that.
            | This could be due to a bug, a slow or failed network, an app bug or other changes to the system.
          p
            | If you feel this is a bug we at the Amahi Team would like to hear from you via the &nbsp;
            a href="https://forums.amahi.org" forums
            | &nbsp; the &nbsp;
            a href="https://bugs.amahi.org" bug tracker
            | &nbsp; or the &nbsp;
            a href="http://talk.amahi.org" IRC support channel
            | .
          p
            | It will help if you can share the logs (in Linux, via terminal or SSH) using "apaste" as follows:             
            code
              | tail -600 /var/log/amahi-app-installer.log | apaste
          p
            | Visit our wiki for further
            a href="https://wiki.amahi.org/index.php/App_Install"  app installation troubleshooting
            | .

plugins/040-apps/app/views/apps/_app_installed.html.slim
- app = app_installed

= content_tag 'div', :class => 'app', :id => "app_whole_#{app.identifier}", :data => { :progress_path => apps_engine.uninstall_progress_path(app.identifier) } do

  table.settings.stretchtoggle[id="app_row_#{app.identifier}"]
    tr.hover-style
      td.settings-col1.settings-col1-pad1.apps-col1
        = link_to name_with_warning(app), '#'
      td.settings-col2.apps-col2.p-1[id="app_ip_#{app.identifier}"]
        = short_desc(app)

  .settings-stretcher[id="app_info_#{app.identifier}" style="#{display_style}"]
    .app-manage.collapsed-div-style.f-size13.text-secondary
      fieldset
        legend &nbsp; #{app.name} #{t('installed_paren')} &nbsp;
        .settings-fields.row
          .img-wrap.col-md-6.col-xs-12.col-sm-12.align-items-center.mb-2
            = app.webapp ? link_to(image_for_app(app), app.remote_url, :target => '_blank', :style=>'width: 100%;') : image_for_app(app)

          .app-content.m-0.col-md-6.col-xs-12.col-sm-12
            div.app-description 
              = app.description.try(:html_safe) || t('no_description_supplied')

            = render 'is_installed', :app => app

            .app-more
              | #{t('version')}:&nbsp;#{app.version}&nbsp;&nbsp;&raquo;&nbsp;
              = link_to '', app.app_url, :target => '_blank', :class=>'glyphicon glyphicon-plus'
              br
              - if app.forum_url.present?
                br
                = link_to "#{t('discussion_forum_for')} #{app.name}", app.forum_url, :target => '_blank'
                | &raquo;

            - unless app.live?
              br
              p
              em
                sup*
                = t('warning_this_application_is_in_testing')

        .app-flash-notice[id="app_legend_#{app.identifier}" style="display:none;"]
          | #{app.name} #{t('is_now_installed')}

= javascript_include_tag 'apps'

plugins/040-apps/app/views/apps/_in_dashboard.html.slim
= simple_remote_checkbox :id => "in_dashboard_#{app.id}",
                         :css_class => 'in_dashboard_checkbox',
                         :url => apps_engine.toggle_in_dashboard_path(:id => app.identifier),
                         :label => "&nbsp; List in dashboard &nbsp;",
                         :checked => app.show_in_dashboard

plugins/040-apps/app/views/apps/_is_available.html.slim
= spinner
span.install
    = link_to(t("install"), apps_engine.install_path(:id => app.identifier), :method => :post, :remote => true, :class => 'install-app-in-background btnn btn btn-info btn-sm ')
span.message.m-3.mt-4 style="display:none;"
	= "message"

plugins/040-apps/app/views/apps/_is_installed.html.slim
- if app.initial_user and ! app.initial_user.blank?
  fieldset.m-0.mt-3
	legend &nbsp; #{t('initial_user_info')} &nbsp;
	blockquote
	  span.initial-user-more &raquo;
	  a href="http://wiki.amahi.org/index.php/Initial_user" target="_blank"
	    = theme_image_tag('more.png', :title => t('more'))
	| #{t('initial_user')}:&nbsp;
	code= app.initial_user || "(blank)"
	br
	| #{t('initial_password')}:&nbsp;
	code= app.initial_password || "(blank)"
	p

- if app.special_instructions and ! app.special_instructions.blank?
  fieldset
    legend &nbsp; #{t('special_instructions')} &nbsp;
    = app.special_instructions.html_safe


- if app.webapp
  div.app-url= link_to(app.full_url, app.full_url, :target => '_blank', :class => 'f-size22')
  = render 'in_dashboard', :app => app

- if app.plugin
  div.app-url= link_to(app.plugin.name, app.plugin.path, :target => '_blank', :class => 'f-size22')
  = spinner

- if app.theme
  div.app-url= link_to(t('manage_themes'), settings_engine.themes_path, :class => "btn btn-info btn-sm f-size22")

br
br

span.progress-status.bg-white.ml-5
  - unless app.has_dependents?
    span.install-button
      = link_to("#{t('uninstall')} &raquo;".html_safe, apps_engine.uninstall_path(:id => app.identifier), :method => :post, :remote => true, :class => 'uninstall-app-in-background btn-sm', :style => 'height: auto;')

.progress.progress-bar-div.mt-4 style="width: 100%; display: none; background: #c7c7c7;"
  .progress-bar.progress-bar-striped.progress-bar-animated.bg-info aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" style="width: 0%; height: 100%;"
    = "0%"

- unless app.installed
  br
  p
    b
      | [!]#{t('warning')}:
  em #{t('this_application_install_ended_with_an_error_please_uninstall_status_is')} #{app.install_status} ("#{app.install_message}")

plugins/040-apps/app/views/apps/_subtabs.html.slim
ul.prefsubtab
  li[class="#{subtab_class('index')} first"]= link_to t('available'), apps_path
  li[class="#{subtab_class('installed')} #{advanced? ? 'other' : 'last'}"]= link_to t('installed'), installed_apps_path
  - if advanced?
    li[class="#{subtab_class('webapps')} last"]= link_to t('webapps'), '#'

plugins/040-apps/app/views/apps/index.html.slim
.app-store-header.row
  .col-xs-6.col-sm-6.col-md-6.col-lg-6.get-apps = link_to 'Get apps', 'https://www.amahi.org/apps', :title => 'Amahi App Store', :target => '_blank', :id => 'btn-get-apps'
  .col-xs-6.col-sm-6.col-md-6.col-lg-6.install-apps = link_to 'Install here!', apps_engine.root_path, :title => 'Refresh', :id => 'btn-install-apps'

#apps-table
  .settings-table
    - if @apps.any?
      table.settings
        tr
          th.settings-col1.settings-col1-pad1.apps-col1[scope='col']= t('application')
          th.settings-col2.pl-2.apps-col2[scope='col'] = t('description')
      = render :partial => 'apps/app_available', :collection => @apps
    - else
      div.align-center.default-message
        h2= t('there_are_no_applications_available')
        p=  t('this_could_be_due_to_lack_of_network_connectivity')

= javascript_include_tag 'apps'

plugins/040-apps/app/views/apps/installed.html.slim
.app-store-header.row
  .col-xs-6.col-sm-6.col-md-6.col-lg-6.get-apps = link_to 'Get apps', 'https://www.amahi.org/apps', :title => 'Amahi App Store', :target => '_blank', :id => 'btn-get-apps'
  .col-xs-6.col-sm-6.col-md-6.col-lg-6.install-apps = link_to 'Install here!', apps_engine.root_path, :title => 'Refresh', :id => 'btn-install-apps'
#apps-table
  .settings-table
    - if @apps.any?
      table.settings
        tr
          th.settings-col1.settings-col1-pad1.apps-col1[scope='col']= t('application')
          th.settings-col2.apps-col2[scope='col']= t('description')
      = render :partial => 'apps/app_installed', :collection => @apps
    - else
      div.align-center.default-message
        h2 = t('there_are_no_applications_installed')
        p = link_to(t('try_installing_some_apps'), apps_engine.root_path)